In [123]:
import numpy as np
from numpy import linalg 

In [124]:
#input A(symmetric N,N), v, m<n
#output V(m+1) T(m)

In [125]:
def lanczos(A,v,m):
    n = A.shape[0]
    a = np.zeros(m)
    b = np.zeros(m)
    V = np.zeros([n,m+1])
    v0 = 0
    V[:,0] = v/np.linalg.norm(v)
    temp = 0
    for i in range(m):
        if(i==0):
            temp = A.dot(V[:,i])
        else:
            temp = A.dot(V[:,i]) - b[i-1]*V[:,i-1]
        a[i] = V[:,i].T.dot(temp)
        temp = temp - a[i]*V[:,i]
        b[i] = np.linalg.norm(temp)
        if(b[i]==0 and (i!=m-1)):
            print("breakdown")
            break
        else:
            V[:,i+1] = temp/b[i]
    for i in range(1,m):
        print(np.sum((A@V[:,i] - (a[i]*V[:,i] + b[i-1]*V[:,i-1] + b[i]*V[:,i+1]))))
    return V , a, b

In [126]:
# to solve the Ax = b 
# lot of stuff for tridiagonal symmetric matrix but using thomas(can't utilise the symmetric fact)
def thomas(A,b):
    n = A.shape[0]
    p = np.zeros(n)
    q = np.zeros(n)
    p[0] = -1*A[0,1]/A[0,0]
    q[0] = b[0]/A[0,0]
    for i in range(1,n-1):
        temp = (A[i,i]+A[i,i-1]*p[i-1])
        p[i] = -1*A[i,i+1]/temp
        q[i] = (b[i]-A[i,i-1]*q[i-1])/temp
    temp = (A[n-1,n-1]+A[n-1,n-2]*p[n-2])
    q[n-1] = (b[n-1]-A[n-1,n-2]*q[n-2])/temp
    u = np.zeros(n)
    u[n-1] = q[n-1]
    for j in range(n-2,-1,-1):
        u[j] = p[j]*u[j+1] + q[j]
    return u

In [127]:
A = np.array([[1,2,0,0,0],[2,2,1,0,0],[0,1,3,2,0],[0,0,2,4,1],[0,0,0,1,5]])

In [128]:
b = np.array([2,1,4,5,2])

In [129]:
x = np.linalg.solve(A, b)

In [130]:
x

array([-1.03225806,  1.51612903,  0.03225806,  1.19354839,  0.16129032])

In [131]:
y = thomas(A,b)

In [132]:
y

array([-1.03225806,  1.51612903,  0.03225806,  1.19354839,  0.16129032])

In [133]:
A1 = np.random.rand(10,10) 
A = A1+A1.T
binitial = np.random.rand(10)
x0 = np.random.rand(10)

In [152]:
m = 10 #value of m has to be adjusted
V,a,b = lanczos(A,x0,m)
T = np.diag(a,0)+np.diag(b[:m-1],-1)+np.diag(b[:m-1],1)
r = A.dot(x0) - binitial
e = np.zeros(m)
e[0] = 1
b1 = np.linalg.norm(r)*e
y = thomas(T,b1)
x = x0 + V[:,:m].dot(y)
print(np.sum(A@V[:,:m]-V[:,:m]@T))
print(A@V[:,:m]@y)

-6.66133814775e-16
0.0
-8.32667268469e-17
-1.38777878078e-16
2.08166817117e-17
2.77555756156e-17
9.71445146547e-17
2.77555756156e-17
-2.77555756156e-17
2.58391434673e-06
[ 2.06782079  1.54653179  5.51174991  0.91540047  1.04589131  4.07502584
  0.41323382  1.67426985  0.08815662  0.87055102]


In [153]:
s = np.linalg.solve(A, binitial)

In [154]:
np.linalg.norm(A@x0 - binitial)

7.7022254459174544

In [155]:
np.linalg.norm(A@x - binitial)

14.008750534240518

In [156]:
x-s

array([-0.61435044,  3.15374104, -0.61948103, -0.39874448, -5.6493444 ,
        1.2004501 , -5.93604139,  5.98635995,  1.53329284,  6.34036448])